language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pytest --cov=package_name test/
after_success:
  - coveralls